name: CI
on:
  push:
    branches: 
      - source
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: setup node
      uses: actions/setup-node@master
    
    - name: checkout boilerplate
      uses: actions/checkout@v2
      with:
        repository: DiscreteTom/dt-blog-boilerplate
      
    - name: checkout blog
      uses: actions/checkout@v2
      with:
        ref: source
        
    - name: npm install & generate
      run: |
        cp discretetom.github.io/* dt-blog-boilerplate
        cd dt-blog-boilerplate
        npm install
        npm run generate
    
    - name: GitHub Pages Deploy
      uses: maxheld83/ghpages@v0.2.1
      env:
        BUILD_DIR: dt-blog-boilerplate/dt-blog-boilerplate/dist
      
