name: CI
on:
  push:
    branches: 
      - source
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: setup node
      uses: actions/setup-node@master
    
    - name: checkout boilerplate
      uses: actions/checkout@v2
      with:
        repository: DiscreteTom/dt-blog-boilerplate
        path: boilerplateRepo
      
    - name: checkout blog
      uses: actions/checkout@v2
      with:
        ref: source
        path: contentRepo
        
    - name: npm install & generate
      run: |
        tree
        cp -r contentRepo/* boilerplateRepo
        cd boilerplateRepo/dt-blog-boilerplate
        npm install
        npm run generate
    
    - name: GitHub Pages Deploy
      uses: maxheld83/ghpages@v0.2.1
      env:
        BUILD_DIR: boilerplateRepo/dt-blog-boilerplate/dist
      
